version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependencies
  ignore:
  - dependency-name: commons-io:commons-io
    versions:
    - 2.8.0
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
