version: '3.7'
services:
  replication-solr:
    image: cnxta/replication-solr:0.3.0-SNAPSHOT
    ports:
      - "8983:8983"
    volumes:
      - replication-data:/var/solr
    networks:
      - replication
    entrypoint:
      - bash
      - "-c"
      - "precreate-core replication_item; precreate-core replication_site; precreate-core replication_status; precreate-core replication_config; exec solr -f"
volumes:
  replication-data:
    external: true
    name: replication-data
networks:
  replication:
    external: true
    name: replication