version: '3.7'
services:
  replication-solr:
    image: r.ion.phx.connexta.com/replication-solr:0.3.0-SNAPSHOT
    ports:
      - "8983:8983"
    volumes:
      - replication-data:/var/solr
    networks:
      - replication
volumes:
  replication-data:
networks:
  replication: